### ISSUE TITLE
Add : eGG Network?

### ISSUE THREAD

**Issue by oldpoem** [samleong123/mewatchsg#17]
Hi
 Would you please add eGG network? It's free on mewatch and epg is available in 
https://iptv-org.github.io/epg/guides/my.xml

Best regards

**Comment by samleong123** [comment]
Hi , thank you for providing the EPG source
But the EPG you provided is only for MY instead of SG 
Normal IPTV players can't merge two EPG (New Tivimate v4.0 with Premium can if im not mistaken)
The SG EPG under same repo do not have eGG Network

**Comment by samleong123** [comment]
eGG Network & oktolidays has been added , please refresh / reimport / update your playlist
Do note that this is without EPG

**Comment by oldpoem** [comment]
Thank you!  I'm using Tivimate premium & OTT Navigator  premium and both support multiple EPG source.  Don't know any normal iptv players that support DRM so it won't play on those players anyway.

Also this kid/key for eGG.
e90f3d78a43d4763bc2e4da2dd418fd2:ffeaf48029791d1687c5fdc09a77e78e

**Comment by oldpoem** [comment]
Also this is epg xml for mewatch.sg including eGG.

https://iptv-org.github.io/epg/guides/sg/mewatch.sg.epg.xml

It includes mewatch free channels except oktoholiday.  Because it created config 8 months ago and not update since.

**Comment by samleong123** [comment]
> Author

will change the EPG source , thanks
