### ISSUE TITLE
tvg-id does not match

### ISSUE THREAD

**Issue by ivan98** [samleong123/mewatchsg#18]
tvg-id does not match that from AqFad2811 EPG.
Example: "Channel 5" does not match "Ch 5" that is used in AqFad2811 EPG.

**Comment by samleong123** [comment]
The tvg-id should be matched with AqFad2811's EPG via this [playlist](https://github.com/samleong123/mewatchsg/raw/main/mewatchsg_drm_wv_url.m3u8)
