### ISSUE TITLE
No EPG now

### ISSUE THREAD

**Issue by kentanttw** [samleong123/mewatchsg#19]
Hi, can I check whether is it possible to get the EPG of the MediaCorp tv channels?

**Comment by samleong123** [comment]
The EPG should be available , please refresh / reimport ur playlist

**Comment by kentanttw** [comment]
Dear Sam,

I tried to delete the URL and put in the URL. I think still cannot get the EPG.

**Comment by samleong123** [comment]
> Dear Sam,
> 
> I tried to delete the URL and put in the URL. I think still cannot get the EPG.

Weird , it work wells at my side
