### ISSUE TITLE
MediaCorp Ch 5 not working

### ISSUE THREAD

**Issue by kentanttw** [samleong123/mewatchsg#22]
Hi, it seems that MediaCorp Ch 5 cannot be open now. Invalid.

**Comment by samleong123** [comment]
![image](https://github.com/samleong123/mewatchsg/assets/58818070/bc55c34f-15f9-4dd5-90f2-62c685ec948a)
Works on my side
Maybe try refreshing / updating the playlist?

**Comment by kentanttw** [comment]
I think it does not work with the extreme player. Other players ok.

**Comment by samleong123** [comment]
Hi, retested on my side and still work. Perhaps you could check with using browser and play the MPD with license URL manually input to the player?
extension://cjfbmleiaobegagekpmlhmaadepdeedn
Can use this extension to test

**Comment by kentanttw** [comment]
Hi, now MediaCorp channel 5 is working. How to use the extension? Just copy and paste the whole link to the player?
By the way, do you know how to play with .php file?

**Comment by samleong123** [comment]
Can install the extension from [Chrome Web Store](https://chromewebstore.google.com/detail/native-mpeg-dash-+-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn?pli=1)
`.php` is a server-side language filename extension, if the content of the `.php` is HLS stream then you may play it in the extension as well.

**Comment by kentanttw** [comment]
Hi,If I am using .php in a tv box, any player to recommend? Extreme player? How to add the .php file?On 21 Jul 2024, at 7:44 PM, Sam Sam ***@***.***> wrote:﻿
Can install the extension from Chrome Web Store
.php is a server-side language filename extension, if the content of the .php is HLS stream then you may play it in the extension as well.
