### ISSUE TITLE
Mewatch EPG need to be update

### ISSUE THREAD

**Issue by djalkam** [samleong123/mewatchsg#24]
From now on, Singapore EPG data will be using channel names as XMLTV ID. These channels have EPG data:

Ch 5
Ch 8
Ch U
Suria
Vasantham
CNA

**Comment by samleong123** [comment]
Hi , fixed on backend. The next updates should uses the latest XMLTV ID as mentioned above.

**Comment by djalkam** [comment]
EPG information not accurate

**Comment by samleong123** [comment]
EPG is maintained by [AqFad2811/epg](https://github.com/AqFad2811/epg/) 
Please create an issue there. Thanks
