### ISSUE TITLE
can you show what http user agent the m3u8 file uses?

### ISSUE THREAD

**Issue by ZebyWebby** [samleong123/mewatchsg#26]
It doesn't play when I put it as a M3U8 file in Jellyfin for live tv. And I might need the HTTP user agent that the file uses.

**Comment by samleong123** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
