### ISSUE TITLE
Black Screen when open olympic channels in VLC

### ISSUE THREAD

**Issue by FakeIP1** [samleong123/mewatchsg#27]
![image](https://github.com/user-attachments/assets/dc08edc2-a25e-444e-89e7-a7916149ba1f'
For some unknown reason, I can't watch anything, it just a black screen.

**Comment by samleong123** [comment]
DRM is not supported by VLC, kindly use this [extension](https://chrome.google.com/webstore/detail/cjfbmleiaobegagekpmlhmaadepdeedn) to play the manifest and key in the license URL manually from [here](https://github.com/samleong123/mewatchsg/blob/main/mewatchsg_drm_wv_url.m3u8)
