### ISSUE TITLE
Black screen when open paris 2024 channel 3

### ISSUE THREAD

**Issue by FakeIP1** [samleong123/mewatchsg#28]
![image](https://github.com/user-attachments/assets/4474868f-5208-4682-8201-42a1499225ac)
The license and stream link is correct. But I can watch other channel

**Comment by fnowegwoenvwoenboiwenbpewm** [comment]
Also having this issue with channel 3,4,7,9,10,11,13,17
Using tivimate and getting error code 403 😞

**Comment by samleong123** [comment]
meWATCH has enabled geoblock for all it's Paris 2024 channels. Please use Singapore VPN to watch it temporarily,

**Comment by samleong123** [comment]
A temporary workaround has been implemented. For those who encountered a 403 issue, please update the playlist again. Tested on OTT Player on 31/7/2024 at 16:48 MYT.
