### ISSUE TITLE
Channels not available at the moment

### ISSUE THREAD

**Issue by djalkam** [samleong123/mewatchsg#29]
Source error: ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED

**Comment by samleong123** [comment]
No problem on my side so far , tested with Tivimate
Please check whether your player support *custom HTTP header* function , as a custom HTTP header is required for all Paris 2024 Channels [here](https://github.com/samleong123/mewatchsg/issues/28#issuecomment-2259995187)

**Comment by djalkam** [comment]
Guess M3UIPTV doesnt support it. Works fine with Tivimate but the malaysia channel TV2 showing error 401. Link https://rtm.samsam123.name.my/rtm-live.m3u8
But playimg fine in RTMKlik without vpn use.

**Comment by samleong123** [comment]
[rtm-live](https://github.com/samleong123/rtm-live) is archived and not maintained anymore. Please use [weareblahs/freeview](https://github.com/weareblahs/freeview) source.
