### ISSUE TITLE
Still blackscreen although the olympic is updated

### ISSUE THREAD

**Issue by FakeIP1** [samleong123/mewatchsg#30]
![image](https://github.com/user-attachments/assets/86894319-f4ac-495f-ab1a-22dfe3a65417)
Can't open it in chrome

**Comment by samleong123** [comment]
As mentioned in issue [28](https://github.com/samleong123/mewatchsg/issues/28#issuecomment-2258620377) , you have to use Singapore VPN (on browser) OR use *3rd party IPTV Player* (such as Tivimate or OTT Player)
Any requests originated from non-SG IP will return 403 error (excepts attached headers from the playlist or use VPN)

**Comment by s7ac** [comment]
Hello, thank you for telling me Can it be done without vpn singapore If so, what about it? im newbie thank again

**Comment by samleong123** [comment]
> Hello, thank you for telling me Can it be done without vpn singapore If so, what about it? im newbie thank again

use 3rd party IPTV Player such as Tivimate or OTT Player)

**Comment by s7ac** [comment]
im try tivimate but cant and  ott player Can't even open the list give error

**Comment by samleong123** [comment]
> im try tivimate but cant and ott player Can't even open the list give error

Just tested, the custom HTTP header method is no longer work. Using Singapore VPN is the only workaround.

**Comment by FakeIP1** [comment]
error 403 again on tivimate

**Comment by samleong123** [comment]
> error 403 again on tivimate

Please refer to the previous comment
