### ISSUE TITLE
Ch 5 and Ch U

### ISSUE THREAD

**Issue by kentanttw** [samleong123/mewatchsg#8]
No longer works on tivimate.

**Comment by samleong123** [comment]
No issue on myside

**Comment by kentanttw** [comment]
Seems working again but took a while for the channels to load. Not so stable.

**Comment by samleong123** [comment]
Takes a while for the channels to load because all of the channels is
Widevine encrypted and takes time to decrypt

**Comment by kentanttw** [comment]
Now channel 5 cannot work in tivimate but strangely can work in OTT Navigator

**Comment by samleong123** [comment]
work on my side for Channel 5 with Tivimate (Custom User Agent set as iPad Chrome UA) & Web Player

**Comment by kentanttw** [comment]
Hi, there is no more program list for the live tv channels.
